const products = [
  {
    image: "/imageCon/kh/kh1.png",
    name: "1. Brohok Ktis",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh2.png",
    name: "2. Nom Banh Jok ",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh3.png",
    name: "3. Kor Ko",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh4.png",
    name: "4. Bay Sac Jruk",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh5.png",
    name: "5. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh6.png",
    name: "6 Mju Krerng Sac Ko",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh7.png",
    name: "7. Kuy Teav",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh8.png",
    name: "8. Kuy Teav",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh9.png",
    name: "9. Kuy teavt Khor Ko",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh10.png",
    name: "10. Janang",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh11.png",
    name: "11. Brohok Ktis",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh12.png",
    name: "12. Brohok Jrunh",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },

  {
    image: "/imageCon/kh/kh13.png",
    name: "13. Kary",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh14.png",
    name: "Nhorm",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh15.png",
    name: "15. Bro hok Ktis",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh16.png",
    name: "16. Mju Youn",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh17.png",
    name: "17. TongYam",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh18.png",
    name: "18. Cha Kdav",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
