const products = [
  {
    image: "/imageCon/kh/kh1.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh2.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh3.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh4.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh5.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh6.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh7.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh8.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh9.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh10.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh11.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh12.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh12.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh13.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh14.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh15.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh16.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh17.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh18.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
