const products = [
  {
    image: "/imageCon/fastFood/ff1.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/kh/kh12.png",
    name: "1. Fresh Lok Lak",
    description: "Khmer Traditional food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff2.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff3.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff4.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff5.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff6.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff7.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff8.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff9.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff10.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff11.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff12.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastFood/ff13.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
