const products = [
  {
    image: "/imageCon/fastfood/ff1.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff2.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff3.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff4.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff5.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff6.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff7.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff8.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff9.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff10.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff11.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff12.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff13.png",
    name: "1. Fresh Lok Lak",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
