const products = [
  {
    image: "/imageCon/fastfood/ff1.png",
    name: "1. Nom Pang Sac",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff2.png",
    name: "2 Mi Cha",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff3.png",
    name: "3. Bay Bak Thom",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff4.png",
    name: "4. Sac Ko Ang",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff5.png",
    name: "5. Sayor",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff6.png",
    name: "6. Morn Bompong",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff7.png",
    name: "7. Burger",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff8.png",
    name: "8. Hotdog",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff9.png",
    name: "Fries Potato",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff10.png",
    name: "10. Nom pea",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff11.png",
    name: "11. Lot",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff12.png",
    name: "12 Shushi",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/fastfood/ff13.png",
    name: "13. Bay morn",
    description: "Fast food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
