const products = [
  {
    image: "/imageCon/eu/eu1.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu2.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu3.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu4.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu5.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu6.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu7.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu8.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu9.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu10.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu11.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu12.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu13.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu14.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu15.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu16.png",
    name: "1. Fresh Lok Lak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
