const products = [
  {
    image: "/imageCon/eu/eu1.png",
    name: "1. Beef Steak",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu2.png",
    name: "2.	Spaghetti Bolognese",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu3.png",
    name: "3. Lasagna",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu4.png",
    name: "4. Pasta Carbonara",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu5.png",
    name: "5.Chicken Cordon Bleu",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu6.png",
    name: "6.Paella",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu7.png",
    name: "7.Bouillabaisse",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu8.png",
    name: "8.Moussaka",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu9.png",
    name: "9.Coq au Vin",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu10.png",
    name: "10. Pork Schnitzel",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu11.png",
    name: "11. Goulash",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu12.png",
    name: "12. Seafood Risotto",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu13.png",
    name: "13. Stuffed Bell Peppers",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu14.png",
    name: "14.	Bruschetta",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu15.png",
    name: "15. Tortilla Española",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/eu/eu16.png",
    name: "16. 	Gratin Dauphinois",
    description: "A Foriegn Food",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
