const products = [
  {
    image: "/imageCon/drink/dr1.png",
    name: "1. Matcha",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr2.png",
    name: "2. Espresso",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr3.png",
    name: "3. Americano",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr4.png",
    name: "4. Cappuccino",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr5.png",
    name: "5. Latte",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr6.png",
    name: "6. Mocha",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr7.png",
    name: "7. Khmer Tea",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr8.png",
    name: "8. Chamomile Tea",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr9.png",
    name: "9. Strawberry Smoothies",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr10.png",
    name: "10. Blueberry Smoothies",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr11.png",
    name: "11. Dragon fruit Smoothies",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr12.png",
    name: "12. Pineapple Smoothies",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr13.png",
    name: "13. Smoothies",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr14.png",
    name: "14. Hot Chocolate",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr15.png",
    name: "15. Fresh Coconut",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
