const products = [
  {
    image: "/imageCon/drink/dr1.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr2.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr3.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr4.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr5.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr6.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr7.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr8.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr9.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr10.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr11.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr12.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr13.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr14.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
  {
    image: "/imageCon/drink/dr15.png",
    name: "1. Fresh Lok Lak",
    description: "Recommend Drink",
    price: "8.99",
    star: "⭐⭐⭐⭐⭐",
    rating: 4.5,
  },
];
export default products;
